[theme]
# A dark-blue primary accent color for interactive elements
primaryColor = "#0d47a1"

# A light "white-blue" background color for the main content area
backgroundColor = "#94B9AF"

# A lighter background color for the sidebar and other components
secondaryBackgroundColor = "#FCF7F8"

# A darker text color for better contrast against the light background
textColor = "#000000"
